### ISSUE TITLE
Crash when running with Tinker Steelworks

### ISSUE THREAD

**Issue by IAmMarauder** [LoveHoly/Ex-Astris#15]
Hi there, 

I am having issues with ExAstris running with TSteelWorks. Here is the full version list of mods (built from a clean install and fresh downloads):
Forge 13.2.1230

Mantle 0.3.2
TConstruct 1.7.1
CookieCore 1.3.0
TSteelworks 1.0.6

Ex-Nihilo 1.37
Ex-Astris 1.12

I did some tests and it all runs fine until I add TSteelworks or ExAstris. Error in next post.

EDIT: Fixed subject to be more meaningful.

**Comment by ephys** [comment]
Looks like the issue is from https://github.com/Ephys/CookieCore, I'll look into it

Edit: isn't, Ex Astris is trying to give a null itemstack to one of the TSteelworks registries
