### ISSUE TITLE
Tinker's Travvelers Boots and Wings Crash

### ISSUE THREAD

**Issue by Iareawsome** [LoveHoly/Ex-Astris#22]
Boots
http://pastebin.com/VfUyfThL

Wings
http://pastebin.com/Y4y7JUZb

**Comment by fuzzl3** [comment]
It's unfortunate, but it happens with any piece of traveller's armor.  Whenever you place any of the armor pieces in the tool station to modify it or the 3x3 table you'll almost instantly crash out with the same error.

**Comment by Zsashas** [comment]
Is there any way around it?

**Comment by fuzzl3** [comment]
Only way we've found was w/o ex asteris.
