### ISSUE TITLE
Automatic Sieve - Ender Io Compatibility Issue

### ISSUE THREAD

**Issue by samalo12** [LoveHoly/Ex-Astris#31]
When extracting items automatically with an item conduit from Ender Io, All upgrades in the Automatic Sieve will also be pulled from the Sieve.

**Comment by MrLightning01** [comment]
use a filter?

**Comment by bochen415** [comment]
...or update to the new maintainer
http://minecraft.curseforge.com/mc-mods/226340-ex-astris/files
