### ISSUE TITLE
Client crash on load

### ISSUE THREAD

**Issue by ariosos** [LoveHoly/Ex-Astris#35]
I have a private custom modpack, which also has ex Nihilo 1.37. I get this when the pack is loading.
http://pastebin.com/rNZBLf8B

There's too many mods to copy each name one by one, but it looks like there's a class file in ex Nihilo that it can't find.

**Comment by TrueKam** [comment]
I can confirm. I'm getting the same error and a CTD. I can post my crash log as well if requested.

**Comment by bochen415** [comment]
http://minecraft.curseforge.com/mc-mods/226340-ex-astris/files
