### ISSUE TITLE
Suggestion: Dust/Gravel/Sand Textures

### ISSUE THREAD

**Issue by nalkrien** [LoveHoly/Ex-Astris#36]
I was wondering if you could, instead of just doing each texture individual hook into Ex Nihilo's texture system that way if anyone does a different texture ie: a faithful texture of the gravel the texture for ex nihilo would automatically be applied to Ex-Astris. Since Ex Nihilo Just does a base Gravel/Dust/Sand Texture then uses a template to do the color change on only the correct part.

**Comment by bochen415** [comment]
https://github.com/MikeLydeamore/Ex-Astris

**Comment by bochen415** [comment]
@LoveHoly Are you back?

**Comment by LoveHoly** [comment]
@bochen415 Yeah. I am back. i devloping new build.
