### ISSUE TITLE
Sanguine Utilities Crash

### ISSUE THREAD

**Issue by Alex-hawks** [LoveHoly/Ex-Astris#41]
In Sanguine Utilities, I iterate over the list of altar recipes looking for orbs, then doing unchecked casts to IBloodOrb. I intentionally do this unsafe cast to catch what would otherwise be a game-breaking bug so that I may expose it to the author at fault. You have registered an orb fill recipe that does not have an orb as the input and null as the output. You will find it [here](https://github.com/LoveHoly/Ex-Astris/blob/master/src/main/java/ExAstris/Bridge/BloodMagic.java#L17). To fix it, all you need to do is change the last parameter (a true) to a false. 

Related: [OpenEye crashlog](http://openeye.openmods.info/crashes/28442d1d31cb09ef4495577da3b3c8e6)

**Comment by bochen415** [comment]
https://github.com/MikeLydeamore/Ex-Astris
