### ISSUE TITLE
[Question] Additional slots in Automatic Sieve

### ISSUE THREAD

**Issue by einsteinsci** [LoveHoly/Ex-Astris#52]
What do the additional two slots (right below the input) do in the automatic sieve? I ask this here only because I cannot find anything on the wiki or Google.

**Comment by LoveHoly** [comment]
can not support that.

**Comment by einsteinsci** [comment]
I'm not asking for an added feature, I'm just asking what the slots are for.

**Comment by LoveHoly** [comment]
Ah sorry, I understood mistake.

right below the input left Speed Upgrade Slot
right Fortune Upgrade Slot

**Comment by einsteinsci** [comment]
Thank you! That makes sense now.
